targets:
  $default:
    builders:
      drift_dev:
        enabled: false
      drift_dev:analyzer:
        enabled: true
        options: &options
          sql:
            dialect: sqlite
      drift_dev:modular:
        enabled: true
        options: *options
