version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - ci
  - package-ecosystem: pub
    directory: /packages/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:brick
  - package-ecosystem: pub
    directory: /packages/brick_e2e/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:brick
      - test
  - package-ecosystem: pub
    directory: /packages/brick_generator/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:bg
  - package-ecosystem: pub
    directory: /packages/reference_app/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
