version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - ci
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - chore

  # Bricks
  - package-ecosystem: pub
    directory: /bricks/altoke_common/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-common
  - package-ecosystem: pub
    directory: /bricks/altoke_common/reference/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-common
  - package-ecosystem: pub
    directory: /bricks/altoke_entity/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-entity
  - package-ecosystem: pub
    directory: /bricks/altoke_entity/reference/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-entity
  - package-ecosystem: pub
    directory: /bricks/altoke_reactive_caches/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-reactive-caches
  - package-ecosystem: pub
    directory: /bricks/altoke_reactive_caches/reference/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-reactive-caches
  - package-ecosystem: pub
    directory: /bricks/altoke_storage/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - b:altoke-storage
  - package-ecosystem: pub
    directory: /bricks/altoke_storage/reference/altoke_entities_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-altoke-storage
  - package-ecosystem: pub
    directory: /bricks/altoke_storage/reference/altoke_entities_hive_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-altoke-storage
  - package-ecosystem: pub
    directory: /bricks/altoke_storage/reference/altoke_entities_isar_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-altoke-storage
  - package-ecosystem: pub
    directory: /bricks/altoke_storage/reference/altoke_entities_realm_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-altoke-storage
  - package-ecosystem: pub
    directory: /bricks/altoke_storage/reference/altoke_entities_sembast_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-altoke-storage
  - package-ecosystem: pub
    directory: /bricks/altoke_storage/reference/altoke_entities_sqlite_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - feat
      - b:altoke-altoke-storage

  # Legacy brick
  - package-ecosystem: pub
    directory: /packages/brick/hooks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:brick
  - package-ecosystem: pub
    directory: /packages/brick_e2e/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:brick
      - test
  - package-ecosystem: pub
    directory: /packages/reference_app/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/app/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/common/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/element_in_memory_cache/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/tasks/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/tasks_repository/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/tasks_storage/_conditional_dir___use_hive_database___tasks_hive_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/tasks_storage/_conditional_dir___use_isar_database___tasks_isar_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/tasks_storage/_conditional_dir___use_realm_database___tasks_realm_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/tasks_storage/_conditional_dir___use_sembast_database___tasks_sembast_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/tasks_storage/_conditional_dir___use_sqlite_database___tasks_sqlite_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref
  - package-ecosystem: pub
    directory: /packages/reference_app/packages/tasks_storage/tasks_storage/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - p:ref

  # Tools
  - package-ecosystem: pub
    directory: /tools/brick_generator/
    schedule:
      interval: daily
    reviewers:
      - mrverdant13
    labels:
      - build
      - t:brick-gen
