name: altoke_common_brick_hooks
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.52
  path: ^1.9.0
  value_equality_approach:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: d1107caac51f877cc41d1a5df593df2eb8f2ea49
      path: ./tools/value_equality_approach/

dev_dependencies:
  very_good_analysis: ^5.1.0
