name: monorepo

repository: https://github.com/mrverdant13/altoke_app

packages:
  - ./packages/brick/hooks/
  - ./packages/brick_generator/
  - ./packages/reference_app/

scripts:
  # Formatting
  f:
    description: Format a package
    run: dart format .
    packageFilters: {}
    exec:
      concurrency: 1
  F:
    description: Format all packages
    run: melos run f --no-select
  F:ci:
    description: Format all packages (CI)
    run: melos exec --fail-fast -- "dart format --set-exit-if-changed ."

  # Analyzing
  a.d:
    description: Analyze a Dart package
    run: dart analyze --fatal-infos --fatal-warnings
    packageFilters:
      flutter: false
    exec:
      concurrency: 1
      orderDependents: true
  a.f:
    description: Analyze a Flutter package
    run: flutter analyze --fatal-infos --fatal-warnings
    packageFilters:
      flutter: true
    exec:
      concurrency: 1
      orderDependents: true
  A:
    description: Analyze all packages
    run: melos run a.d --no-select && melos run a.f --no-select
  A:ci:
    description: Analyze all packages (CI)
    run: melos exec --fail-fast --order-dependents --no-flutter -- "dart analyze --fatal-infos --fatal-warnings" && melos exec --fail-fast --order-dependents --flutter -- "flutter analyze --fatal-infos --fatal-warnings --no-pub --no-congratulate --no-preamble"

  # Testing & Coverage
  t.d:
    description: Test a Dart package
    run: >
      dart test -x ci-only --coverage=coverage -r expanded --test-randomize-ordering-seed random --color &&
      dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib -b MELOS_PACKAGE_PATH
    packageFilters:
      flutter: false
      dirExists:
        - test
    exec:
      concurrency: 1
      orderDependents: true
  t.f:
    description: Test a Flutter package
    run: flutter test -x ci-only --coverage -r expanded --test-randomize-ordering-seed random
    packageFilters:
      flutter: true
      dirExists:
        - test
    exec:
      concurrency: 1
      orderDependents: true
  T:
    description: Test all packages
    run: melos run t.d --no-select && melos run t.f --no-select
  T:ci:
    description: Test all packages (CI)
    run: melos exec --fail-fast --order-dependents --no-flutter --dir-exists="test" -- "dart test -x ci-only --coverage=coverage -r expanded --test-randomize-ordering-seed random && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib -b MELOS_PACKAGE_PATH" && melos exec --fail-fast --order-dependents --flutter --dir-exists="test" -- "flutter test -x ci-only --coverage -r expanded --test-randomize-ordering-seed random"
  TC:
    description: Merge all packages coverage trace files ignoring data related to generated files.
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info &&
      melos exec --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --paths-parent MELOS_PACKAGE_PATH  --filters \.g\.dart,\.gr\.dart" &&
      coverde check -i coverage/filtered.lcov.info 100

  # Code generation
  g:
    description: Generate code for a package
    run: dart run build_runner build -d
    packageFilters:
      dependsOn:
        - build_runner
    exec:
      failFast: true
      concurrency: 1
  G:
    description: Generate code for all packages
    run: melos run g --no-select

  # Brick management
  BG:
    description: Generate brick
    run: dart run MELOS_ROOT_PATH/packages/brick_generator/lib/main.dart
  BA:
    description: Add brick globally
    run: mason add -g altoke_app --path MELOS_ROOT_PATH/packages/brick/
  B:
    description: Generate brick and add it globally
    run: melos run BG && melos run BA
