name: local_brick_installer
description: A tool to install bricks managed by a local monorepo.
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  monorepo_elements:
    path: ../monorepo_elements/

dev_dependencies:
  very_good_analysis: ^5.1.0
