name: pubspec_sorter
description: A tool to sort pubspec.yaml files.
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  path: ^1.9.0

dev_dependencies:
  very_good_analysis: ^5.1.0
