name: altoke_app
description: An Altoke App.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3 <4.0.0"

dependencies:
  #*w 1v 2> w*#
  #{{#use_auto_route_router}}#
  auto_route: ^7.8.4
  #*w 1v 2> w*#
  #{{/use_auto_route_router}}#
  common:
    path: ../common/
  #*w 1v 2> w*#
  #{{#use_sqlite_database}}#
  drift: ^2.16.0
  #*w 1v 2> w*#
  #{{/use_sqlite_database}}#
  element_in_memory_cache:
    path: ../element_in_memory_cache/
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  #*w 1v 2> w*#
  #{{#use_go_router_router}}#
  go_router: ^13.2.0
  #*w 1v 2> w*#
  #{{/use_go_router_router}}#
  #{{#use_hive_database}}#
  hive: ^2.2.3
  #*w 1v 2> w*#
  #{{/use_hive_database}}#
  intl: ^0.18.1
  #*w 1v 2> w*#
  #{{#use_isar_database}}#
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  #*w 1v 2> w*#
  #{{/use_isar_database}}#
  json_annotation: ^4.8.1
  meta: ^1.11.0
  path: ^1.8.3
  path_provider: ^2.1.2
  reactive_forms: ^16.1.1
  #*w 1v 2> w*#
  #{{#use_realm_database}}#
  realm: ^1.9.0
  #*w 1v 2> w*#
  #{{/use_realm_database}}#
  riverpod_annotation: ^2.3.4
  #*w 1v 2> w*#
  #{{#use_sembast_database}}#
  sembast: ^3.6.0
  sembast_web: ^2.2.0
  #*w 1v 2> w*#
  #{{/use_sembast_database}}#
  #{{#use_sqlite_database}}#
  sqlite3: ^2.4.0
  sqlite3_flutter_libs: ^0.5.20
  #*w 1v 2> w*#
  #{{/use_sqlite_database}}#
  tasks:
    path: ../tasks/
  #*w 1v 2> w*#
  #{{#use_hive_database}}#
  tasks_hive_storage:
    path: ../tasks_storage/_conditional_dir___use_hive_database___tasks_hive_storage/
  #*w 1v 2> w*#
  #{{/use_hive_database}}#
  #{{#use_isar_database}}#
  tasks_isar_storage:
    path: ../tasks_storage/_conditional_dir___use_isar_database___tasks_isar_storage/
  #*w 1v 2> w*#
  #{{/use_isar_database}}#
  #{{#use_realm_database}}#
  tasks_realm_storage:
    path: ../tasks_storage/_conditional_dir___use_realm_database___tasks_realm_storage/
  #*w 1v 2> w*#
  #{{/use_realm_database}}#
  tasks_repository:
    path: ../tasks_repository/
  #*w 1v 2> w*#
  #{{#use_sembast_database}}#
  tasks_sembast_storage:
    path: ../tasks_storage/_conditional_dir___use_sembast_database___tasks_sembast_storage/
  #*w 1v 2> w*#
  #{{/use_sembast_database}}#
  #{{#use_sqlite_database}}#
  tasks_sqlite_storage:
    path: ../tasks_storage/_conditional_dir___use_sqlite_database___tasks_sqlite_storage/
  #*w 1v 2> w*#
  #{{/use_sqlite_database}}#
  tasks_storage:
    path: ../tasks_storage/tasks_storage/
  universal_io: ^2.2.2

dev_dependencies:
  #*w 1v 2> w*#
  #{{#use_auto_route_router}}#
  auto_route_generator: ^7.3.2
  #*w 1v 2> w*#
  #{{/use_auto_route_router}}#
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  #*w 1v 2> w*#
  #{{#use_sqlite_database}}#
  drift_dev: ^2.16.0
  #*w 1v 2> w*#
  #{{/use_sqlite_database}}#
  flutter_test:
    sdk: flutter
  #*w 1v 2> w*#
  #{{#use_go_router_router}}#
  go_router_builder: ^2.4.1
  #*w 1v 2> w*#
  #{{/use_go_router_router}}#
  #{{#use_isar_database}}#
  isar_generator: ^3.1.0+1
  #*w 1v 2> w*#
  #{{/use_isar_database}}#
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
