name: tasks_repository
description: A repository that manages tasks.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  element_in_memory_cache:
    path: ../element_in_memory_cache/
  meta: ^1.10.0
  tasks:
    path: ../tasks/
  tasks_storage:
    path: ../tasks_storage/tasks_storage/

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0
