name: monorepo

packages:
  - ./packages/app/
  - ./packages/common/
  - ./packages/element_in_memory_cache/
  - ./packages/tasks/
  - ./packages/tasks_repository/
  #*w 1v 2> w*#
  #{{#use_hive_database}}#
  - ./packages/tasks_storage/_conditional_dir___use_hive_database___tasks_hive_storage/
  #{{/use_hive_database}}#
  #{{#use_isar_database}}#
  - ./packages/tasks_storage/_conditional_dir___use_isar_database___tasks_isar_storage/
  #{{/use_isar_database}}#
  #{{#use_realm_database}}#
  - ./packages/tasks_storage/_conditional_dir___use_realm_database___tasks_realm_storage/
  #{{/use_realm_database}}#
  #{{#use_sembast_database}}#
  - ./packages/tasks_storage/_conditional_dir___use_sembast_database___tasks_sembast_storage/
  #{{/use_sembast_database}}#
  #{{#use_sqlite_database}}#
  - ./packages/tasks_storage/_conditional_dir___use_sqlite_database___tasks_sqlite_storage/
  #{{/use_sqlite_database}}#
  #*w 1v 2> w*#
  - ./packages/tasks_storage/tasks_storage/

command:
  #*w 1v 2> w*#
  #{{#use_realm_database}}#
  bootstrap:
    hooks:
      post:
        run: >
          melos exec --depends-on realm -- "dart run realm install"
  #*w 1v 2> w*#
  #{{/use_realm_database}}#
  clean:
    hooks:
      pre:
        #*w 1v 8> w*#
        #*replace-start*#
        run: >
          melos exec -- "coverde rm .dart_tool/ build/ pubspec_overrides.yaml"
          &&
          melos exec --depends-on realm -- "coverde rm binary/ default.realm.management default.realm.lock"
        #*with i8*#
        # run: >
        #   melos exec -- "coverde rm .dart_tool/ build/ pubspec_overrides.yaml"
        #   #{{#use_realm_database}}#
        #   #*w 1v 10> w*#
        #   &&
        #   melos exec --depends-on realm -- "coverde rm binary/ default.realm.management default.realm.lock"
        #   #{{/use_realm_database}}#
        #*replace-end*#
        #*w 2v w*#

scripts:
  # Code Generation
  g.d:
    description: Generate code for a package
    run: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn:
        - build_runner
    exec:
      concurrency: 1
      failFast: true
      orderDependents: true
  #*w 1v 2> w*#
  #{{#use_realm_database}}#
  g.r:
    description: Generate Realm code for a package
    run: dart run realm generate
    packageFilters:
      dependsOn:
        - realm
      ignore:
        - altoke_app
    exec:
      concurrency: 1
      failFast: true
      orderDependents: true
  #*w 1v 2> w*#
  #{{/use_realm_database}}#
  G:
    description: Generate code for all packages
    #*w 1v 4> w*#
    #*replace-start*#
    run: >
      melos run g.d --no-select
      &&
      melos run g.r --no-select
    #*with i4*#
    # run: >
    #   melos run g.d --no-select
    #   #{{#use_realm_database}}#
    #   #*w 1v 6> w*#
    #   &&
    #   melos run g.r --no-select
    #   #{{/use_realm_database}}#
    #*replace-end*#
    #*w 2v 2> w*#

  # Formatting
  f:
    description: Format a package
    run: dart format .
    exec:
      concurrency: 1
  F:
    description: Format all packages
    run: melos run f --no-select

  # Analyzing
  a.d:
    description: Analyze a Dart package
    run: dart analyze --fatal-infos --fatal-warnings
    packageFilters:
      flutter: false
    exec:
      concurrency: 1
      orderDependents: true
  a.f:
    description: Analyze a Flutter package
    run: flutter analyze --fatal-infos --fatal-warnings
    packageFilters:
      flutter: true
    exec:
      concurrency: 1
      orderDependents: true
  a.c:
    description: Analyze a package with custom lint rules
    run: dart run custom_lint
    packageFilters:
      dependsOn:
        - custom_lint
    exec:
      concurrency: 1
      orderDependents: true
  A:
    description: Analyze all packages
    run: >
      melos run a.d --no-select &&
      melos run a.f --no-select &&
      melos run a.c --no-select

  # Testing & Coverage
  t.d:
    description: Test a Dart package
    run: >
      dart test -x ci-only --coverage=coverage -r expanded --test-randomize-ordering-seed random --color &&
      dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
    packageFilters:
      flutter: false
      dirExists:
        - test
      dependsOn:
        - test
    exec:
      concurrency: 1
      orderDependents: true
  t.f:
    description: Test a Flutter package
    run: flutter test -x ci-only --coverage -r expanded --test-randomize-ordering-seed random
    packageFilters:
      flutter: true
      dirExists:
        - test
      dependsOn:
        - flutter_test
    exec:
      concurrency: 1
      orderDependents: true
  T:
    description: Test all packages
    run: >
      melos run t.d --no-select &&
      melos run t.f --no-select
  M:
    description: Merge all coverage reports
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info &&
      melos exec -c 1 --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --paths-parent MELOS_PACKAGE_PATH  --filters \.drift\.dart,\.freezed\.dart,\.g\.dart,\.gr\.dart"

  C:
    description: Check coverage
    run: >
      coverde check -i MELOS_ROOT_PATH/coverage/filtered.lcov.info 100
