name: altoke_app
description: An Altoke App.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.13.0

dependencies:
  #*w 1v 2> w*#
  #{{#use_auto_route_router}}#
  auto_route: ^7.8.3
  #*w 1v 2> w*#
  #{{/use_auto_route_router}}#
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #*w 1v 2> w*#
  #{{#use_go_router_router}}#
  go_router: ^10.1.2
  #*w 1v 2> w*#
  #{{/use_go_router_router}}#
  intl: ^0.18.1

dev_dependencies:
  #*w 1v 2> w*#
  #{{#use_auto_route_router}}#
  auto_route_generator: ^7.3.1
  #*w 1v 2> w*#
  #{{/use_auto_route_router}}#
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  #*w 1v 2> w*#
  #{{#use_go_router_router}}#
  go_router_builder: ^2.3.1
  #*w 1v 2> w*#
  #{{/use_go_router_router}}#
  meta: ^1.9.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
