name: altoke_common_e2e
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dev_dependencies:
  mason: ^0.1.0-dev.52
  meta: ^1.12.0
  mocktail: ^1.0.3
  path: ^1.9.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0
