name: altoke_reactive_caches_e2e
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dev_dependencies:
  mason: ^0.1.0-dev.52
  mocktail: ^1.0.3
  monorepo_elements:
    path: ../../../tools/monorepo_elements/
  path: ^1.9.0
  shell:
    path: ../../../tools/shell/
  test: ^1.25.2
  very_good_analysis: ^5.1.0
