name: brick_generator
description: A generator for bricks.
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  meta: ^1.11.0
  monorepo_elements:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: c21ad2087476e3164f4adbf3488daf15fa958be6
      path: ./tools/monorepo_elements/
  path: ^1.9.0
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 1004669066d2eae47de8696387e3179f4b09061f
      path: ./tools/shell/

dev_dependencies:
  very_good_analysis: ^5.1.0
