name: {{project_name.snakeCase()}}
description: {{{project_description}}}
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: 3.16.0

dependencies:
  {{#use_auto_route_router}}auto_route: ^7.8.4
  {{/use_auto_route_router}}common:
    path: ../common/
  {{#use_sqlite_database}}drift: ^2.15.0
  {{/use_sqlite_database}}element_in_memory_cache:
    path: ../element_in_memory_cache/
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.8
  {{#use_go_router_router}}go_router: ^12.1.1
  {{/use_go_router_router}}{{#use_hive_database}}hive: ^2.2.3
  {{/use_hive_database}}intl: ^0.18.1
  {{#use_isar_database}}isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  {{/use_isar_database}}json_annotation: ^4.8.1
  meta: ^1.10.0
  path: ^1.8.3
  path_provider: ^2.1.1
  reactive_forms: ^16.1.1
  {{#use_realm_database}}realm: ^1.6.1
  {{/use_realm_database}}riverpod_annotation: ^2.3.2
  {{#use_sembast_database}}sembast: ^3.5.0+1
  sembast_web: ^2.2.0
  {{/use_sembast_database}}{{#use_sqlite_database}}sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.19+1
  {{/use_sqlite_database}}tasks:
    path: ../tasks/
  {{#use_hive_database}}tasks_hive_storage:
    path: ../tasks_storage/tasks_hive_storage/
  {{/use_hive_database}}{{#use_isar_database}}tasks_isar_storage:
    path: ../tasks_storage/tasks_isar_storage/
  {{/use_isar_database}}{{#use_realm_database}}tasks_realm_storage:
    path: ../tasks_storage/tasks_realm_storage/
  {{/use_realm_database}}tasks_repository:
    path: ../tasks_repository/
  {{#use_sembast_database}}tasks_sembast_storage:
    path: ../tasks_storage/tasks_sembast_storage/
  {{/use_sembast_database}}{{#use_sqlite_database}}tasks_sqlite_storage:
    path: ../tasks_storage/tasks_sqlite_storage/
  {{/use_sqlite_database}}tasks_storage:
    path: ../tasks_storage/tasks_storage/
  universal_io: ^2.2.2

dev_dependencies:
  {{#use_auto_route_router}}auto_route_generator: ^7.3.2
  {{/use_auto_route_router}}build_runner: ^2.4.6
  custom_lint: ^0.5.7
  {{#use_sqlite_database}}drift_dev: ^2.15.0
  {{/use_sqlite_database}}flutter_test:
    sdk: flutter
  {{#use_go_router_router}}go_router_builder: ^2.3.4
  {{/use_go_router_router}}{{#use_isar_database}}isar_generator: ^3.1.0+1
  {{/use_isar_database}}json_serializable: ^6.7.1
  mocktail: ^1.0.1
  riverpod_generator: ^2.3.8
  riverpod_lint: ^2.3.6
  very_good_analysis: ^5.1.0

dependency_overrides:
  analyzer: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
