targets:
  $default:
    builders:
      {{#use_auto_route_router}}auto_route_generator:auto_route_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routing/routes/**
      auto_route_generator:auto_router_generator:
        options:
          enable_cached_builds: true
        generate_for:
          - lib/routing/router.dart{{/use_auto_route_router}}{{#use_go_router_router}}go_router_builder:
        options:
        generate_for:
          - lib/routing/router.dart{{/use_go_router_router}}
