name: monorepo

packages:
  - ./packages/app/
  - ./packages/common/
  - ./packages/element_in_memory_cache/
  - ./packages/tasks/
  - ./packages/tasks_repository/
  {{#use_hive_database}}- ./packages/tasks_storage/tasks_hive_storage/{{/use_hive_database}}{{#use_isar_database}}- ./packages/tasks_storage/tasks_isar_storage/{{/use_isar_database}}{{#use_realm_database}}- ./packages/tasks_storage/tasks_realm_storage/{{/use_realm_database}}{{#use_sembast_database}}- ./packages/tasks_storage/tasks_sembast_storage/{{/use_sembast_database}}{{#use_sqlite_database}}- ./packages/tasks_storage/tasks_sqlite_storage/{{/use_sqlite_database}}
  - ./packages/tasks_storage/tasks_storage/

command:
  {{#use_realm_database}}bootstrap:
    environment:
      sdk: ">=3.3.1 <4.0.0"
      flutter: ">=3.19.3 <4.0.0"
    hooks:
      post:
        run: >
          melos exec --depends-on realm -- "dart run realm install"
  {{/use_realm_database}}clean:
    hooks:
      pre:
        run: melos run clean

scripts:
  # Clean-up
  clean:
    description: Deep clean-up by removing all git-ignored elements.
    run: git clean -dfX .
    exec:
      concurrency: 1

  # Code Generation
  gen:
    description: Generate code for a package
    run: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn:
        - build_runner
    exec:
      concurrency: 1
      failFast: true
      orderDependents: true
  {{#use_realm_database}}gen.realm:
    description: Generate code for a package with Realm
    run: dart run realm generate
    packageFilters:
      dependsOn:
        - realm
      ignore:
        - {{project_name.snakeCase()}}
    exec:
      concurrency: 1
      failFast: true
      orderDependents: true
  {{/use_realm_database}}gen.all:
    description: Generate code for all packages
    run: >
      melos run gen --no-select{{#use_realm_database}}
      &&
      melos run gen.realm --no-select{{/use_realm_database}}

  gen.all.fast:
    description: Generate code for all packages (concurrent)
    run: >
      melos exec --fail-fast --depends-on=build_runner -- "dart run build_runner build --delete-conflicting-outputs"{{#use_realm_database}}
      &&
      melos exec --fail-fast --depends-on=realm --ignore={{project_name.snakeCase()}} -- "dart run realm generate"{{/use_realm_database}}

  # Formatting
  format:
    description: Format a package
    run: dart format .
    exec:
      concurrency: 1
  format.all:
    description: Format all packages
    run: melos run format --no-select
  format.all.fast:
    description: Format all packages (concurrent)
    run: melos exec -- "dart format ."
  format.ci:
    description: Format all packages (CI)
    run: melos exec --fail-fast -- "dart format --set-exit-if-changed ."

  # Analyzing
  analyze.dart:
    description: Analyze a Dart package
    run: dart analyze
    packageFilters:
      flutter: false
    exec:
      concurrency: 1
      orderDependents: true
  analyze.flutter:
    description: Analyze a Flutter package
    run: flutter analyze --no-pub
    packageFilters:
      flutter: true
    exec:
      concurrency: 1
      orderDependents: true
  analyze.custom:
    description: Analyze a package with custom lint rules
    run: dart run custom_lint
    packageFilters:
      dependsOn:
        - custom_lint
    exec:
      concurrency: 1
      orderDependents: true
  analyze.all:
    description: Analyze all packages
    run: >
      melos run analyze.dart --no-select
      &&
      melos run analyze.flutter --no-select
      &&
      melos run analyze.custom --no-select
  analyze.all.fast:
    description: Analyze all packages (concurrent)
    run: >
      melos exec --fail-fast --no-flutter -- "dart analyze"
      &&
      melos exec --fail-fast --flutter -- "flutter analyze --no-pub"
      &&
      melos exec --fail-fast --depends-on=custom_lint -- "dart run custom_lint"
  analyze.ci:
    description: Analyze all packages (CI)
    run: >
      melos exec --fail-fast --no-flutter -- "dart analyze --fatal-infos --fatal-warnings"
      &&
      melos exec --fail-fast --flutter -- "flutter analyze --fatal-infos --fatal-warnings --no-pub --no-congratulate --no-preamble"
      &&
      melos exec --fail-fast --depends-on=custom_lint -- "dart run custom_lint --fatal-infos --fatal-warnings"

  # Testing & Coverage
  test.dart:
    description: Test a Dart package
    run: >
      dart test -x ci-only --coverage=coverage -r expanded --test-randomize-ordering-seed random --color
      &&
      format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib -b MELOS_PACKAGE_PATH
    packageFilters:
      flutter: false
      dirExists:
        - test
      dependsOn:
        - test
    exec:
      concurrency: 1
      orderDependents: true
  test.flutter:
    description: Test a Flutter package
    run: flutter test -x ci-only --coverage -r expanded --test-randomize-ordering-seed random
    packageFilters:
      flutter: true
      dirExists:
        - test
      dependsOn:
        - flutter_test
    exec:
      concurrency: 1
      orderDependents: true
  test.all:
    description: Test all packages
    run: >
      melos run test.dart --no-select
      &&
      melos run test.flutter --no-select
  test.ci:
    description: Test all packages (CI)
    run: >
      melos exec -c 1 --fail-fast --no-flutter --depends-on=test --dir-exists=test -- "dart test -x ci-only --coverage=coverage -r expanded --test-randomize-ordering-seed random && format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib -b MELOS_PACKAGE_PATH"
      &&
      melos exec --fail-fast --flutter --depends-on=flutter_test --dir-exists=test -- "flutter test -x ci-only --coverage -r expanded --test-randomize-ordering-seed random"
  coverage.merge:
    description: Merge all coverage reports
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info
      &&
      melos exec -c 1 --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --paths-parent MELOS_PACKAGE_PATH  --filters \.drift\.dart,\.freezed\.dart,\.g\.dart,\.gr\.dart"
  coverage.check:
    description: Check coverage
    run: >
      coverde check -i MELOS_ROOT_PATH/coverage/filtered.lcov.info 100
