name: altoke_storage_brick_hooks
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.52
  path: ^1.9.0
  pubspec_deps_sorter:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 63c80e3d14f2844bbef5d135b04338da6859a31f
      path: ./tools/pubspec_deps_sorter/

dev_dependencies:
  very_good_analysis: ^5.1.0
