name: altoke_storage_brick_hooks
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  mason: ^0.1.0-dev.52
  path: ^1.9.0
  pubspec_sorter:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: b281e794604458a480764ff1cd08fc781ce58e54
      path: ./tools/pubspec_sorter/

dev_dependencies:
  very_good_analysis: ^5.1.0
