name: tasks_sqlite_storage
description: A persistent storage for tasks built on top of SQLite.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  common:
    path: ../../common/
  drift: ^2.15.0
  meta: ^1.10.0
  tasks:
    path: ../../tasks/
  tasks_storage:
    path: ../tasks_storage/

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  test: ^1.24.9
  very_good_analysis: ^5.1.0
