name: readme_unifier
description: A tool to unify README brick files.
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  path: ^1.9.0

dev_dependencies:
  very_good_analysis: ^5.1.0
