name: readmes_resolver
description: A tool to resolve README files.
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  altoke_monorepo_environment:
    path: ../altoke_monorepo_environment/
  checked_yaml: ^2.0.3
  mason: ^0.1.0-dev.53
  path: ^1.9.0

dev_dependencies:
  very_good_analysis: ^5.1.0
