name: e2e

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/e2e.yaml
      - packages/brick/**
      - packages/brick_e2e/**
      - melos.yaml
      - pubspec.yaml
  workflow_dispatch: {}

jobs:
  e2e:
    name: E2E testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # TODO(mrverdant13): Re-enable macOS and Ubuntu
          # - macos-latest
          # - ubuntu-latest
          - windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.16.0
      - name: Install melos
        run: dart pub global activate melos 3.2.0
      - name: Install coverage
        run: dart pub global activate coverage 1.7.2
      - name: Install coverde
        run: dart pub global activate coverde 0.2.0+2
      - name: Initialize melos
        run: melos bs
      - name: Run E2E tests
        # HACK: E2E tests cannot be run with Melos
        # Check the root melos.yaml for more details
        # run: melos run t.e2e.d
        run: dart test e2e --run-skipped -t e2e -j 1 -r expanded --verbose-trace --chain-stack-traces --test-randomize-ordering-seed=random
        working-directory: packages/brick_e2e
