name: generate_templates

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/generate_root_readme.yaml
      - bricks/**/brick/README.md
      - melos.yaml
      - README.md
      - tools/readme_unifier/**

jobs:
  generate-root-readme:
    name: Generate root README.md
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.3
      - name: Install melos
        run: dart pub global activate melos 5.3.0
      - name: Initialize melos
        run: melos bs
      - name: Generate template
        run: melos run brick.docs
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          add-paths: |
            ./README.md
          branch: docs/update-root-readme
          commit-message: 'docs: update root README'
          title: 'docs: update root README'
          body: Update root README.
          delete-branch: true
          labels: |
            bot
            docs
          author: Altoke Bot <altoke.bot@users.noreply.github.com>
          committer: Altoke Bot <altoke.bot@users.noreply.github.com>
          assignees: mrverdant13
          reviewers: mrverdant13
