name: generate_template

on:
  workflow_dispatch: {}

jobs:
  generate-template:
    name: Format and analyze codebase
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.3
      - name: Install melos
        run: dart pub global activate melos 4.1.0
      - name: Initialize melos
        run: melos bs
      - name: Generate template
        run: melos run brick.gen
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          add-paths: |
            ./packages/brick/__brick__/**
          branch: chore/brick/update-template
          commit-message: 'chore(brick): update template'
          title: 'chore(brick): update template'
          body: Update template.
          delete-branch: true
          labels: |
            bot
            p:brick
          author: Altoke Bot <altoke.bot@users.noreply.github.com>
          committer: Altoke Bot <altoke.bot@users.noreply.github.com>
          assignees: mrverdant13
          reviewers: mrverdant13
